### ISSUE TITLE
Diseñar diagrama de la base de datos

### ISSUE THREAD

**Issue by jcastrov** [BorderlandSoft/OlimpiColombia#1]

**Comment by dhmahecha** [comment]
Adjunto el modelo de datos, se tomo de base el existente, pero se hicieron algunos cambios
[Modelo_datos_OlimpiColombia.docx](https://github.com/BorderlandSoft/OlimpiColombia/files/418946/Modelo_datos_OlimpiColombia.docx)

**Comment by dhmahecha** [comment]
Subo el eap comprimido, por si alguien propone un ajuste
[olimpiColombia.zip](https://github.com/BorderlandSoft/OlimpiColombia/files/418977/olimpiColombia.zip)

**Comment by jwsanabria** [comment]
Me parece que la entidad Deporte no deberia tener modalidad y no estoy seguro del atributo medalla en la entidad modalidades

**Comment by jcastrov** [comment]
## Relaciones
- La relación **Atleta - Modalidades** debe ser muchos a muchos
- Hace falta  una entidad entre **Atleta** y **Competencia**, para registrar el resultado del deportista en la competencia

## Tablas

### Modalidades
- El nombre debe ser **Modalidad**

### Deporte
- Si la columna **archivo** se refiere a la URL de la imagen, esta debe ser de tipo `varchar(1000)`. Es más fácil guardar las imágenes del proyecto en la carpeta `static` y referenciarlas con la URL

### Atleta
- Hace falta la columna **apellidos** en la tabla **Atleta**
- La columna **edad** no es necesaria, ya que se calcula con la fecha de nacimiento
- Hace falta la columna **entrenador**

## Para tener en cuenta a futuro
- Si no es necesario crear la tabla Usuario, y se usa la de seguridad de Django.
- Para la autenticación en Facebook se debe guardar un token en la base de datos

**Comment by jwsanabria** [comment]
Adjunto archivo con el diagrama del modelo de datos modificado teniendo en cuenta las recomendaciones mencionadas: 
[Modelo_datos_OlimpiColombia.docx](https://github.com/BorderlandSoft/OlimpiColombia/files/419163/Modelo_datos_OlimpiColombia.docx)
- Para facilidad en la consulta se agrega relación entre Atleta y Deporte, en cuanto a la recomendación de apellidos en el Atleta, me parece que es mas simple por el tamaño del ejercicio manejar un solo nombre completo.

**Comment by dhmahecha** [comment]
Ajunto modelo según las recomendaciones
[Modelo_datos_OlimpiColombia.docx](https://github.com/BorderlandSoft/OlimpiColombia/files/419368/Modelo_datos_OlimpiColombia.docx)
[olimpiColombia.zip](https://github.com/BorderlandSoft/OlimpiColombia/files/419369/olimpiColombia.zip)

**Comment by dhmahecha** [comment]
Nuevamente se hizo un cambio teniendo en cuenta que la relación entre atleta y modalidad debería tener una tabla intermedia

[Modelo_datos_OlimpiColombia.docx](https://github.com/BorderlandSoft/OlimpiColombia/files/421785/Modelo_datos_OlimpiColombia.docx)

**Comment by jwsanabria** [comment]
![model_olimpicolombia](https://cloud.githubusercontent.com/assets/1524150/17834587/384b40ee-670d-11e6-9960-66dd7161d0f8.png)
